name: E2E tests / Locally

on:
  schedule:
    - cron: '0 0 * * *'
  push: # TODO: remove
    branches:
      - 'rfc-18/**'
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - name: Install common tools
        working-directory: ./deployments/local-setup-environment/provisioning/
        run: ./install-commons.sh

      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-solidity-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
          
      - name: Install Go
        working-directory: ./deployments/local-setup-environment/provisioning/
        run: |
          sudo rm -rf /usr/local/go
          ./install-go.sh
          echo "Using Go: $(go version)"
          echo "GOPATH=$HOME/go" >> $GITHUB_ENV

      # Below step cannot be combined with the above, as $GOPATH env variable
      # becomes available only after above step gets executed.
      - name: Append PATH variable
        run: |
          echo "/usr/local/go/bin" >> $GITHUB_PATH
          echo "$GOPATH/bin" >> $GITHUB_PATH
         
      - name: Install Geth
        working-directory: ./deployments/local-setup-environment/provisioning/
        run: ./install-geth.sh

      - name: Install Solidity
        working-directory: ./deployments/local-setup-environment/provisioning/
        run: ./install-solidity.sh

      - name: Install Protobuf
        working-directory: ./deployments/local-setup-environment/provisioning/
        run: ./install-protobuf.sh

      - name: Initialize and run Geth
        run: |
          ./initialize-geth.sh
          ./run-geth.sh &

      - name: Run Bitcoin Core and ElectrumX
        run: ./run-bitcoin.sh &

      - name: Run pre-install script
        run: ./pre-install.sh

      - name: Run install script
        run: |
          export E2E_TEST=true
          ./install.sh

      - name: Run Core and ECDSA clients
        run: |
          ./run-core-1.sh &
          ./run-ecdsa-1.sh &
          ./run-ecdsa-2.sh &
          ./run-ecdsa-3.sh &

      - name: Use Node.js 14.17.0
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'

      - name: Prepare environment for running E2E test scripts
        run: ./install-e2e-test.sh

      - name: Run E2E test scripts
        run: ./run-e2e-test.sh
