name: E2E tests / Locally

on:
  schedule:
    - cron: '0 0 * * *'
  push: # TODO: remove
    branches:
      - 'rfc-18/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deployments/local-setup-environment/provisioning/
        shell: bash
    steps:
      - uses: actions/checkout@v2
        # with:
        #   path: local-setup

      - name: DEBUG - show github.workspace
        run: echo ${{ github.workspace }}

      - name: DEBUG - ls in github.workspace
        working-directory: ${{ github.workspace }}
        run: ls

      - name: Install common tools
        run: ./install-commons.sh

      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-solidity-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
          
      - name: Install Go
        run: |
          sudo rm -rf /usr/local/go # needed?
          ./install-go.sh
          echo "Using Go: $(go version)"

      - name: Set GOPATH variable
        run: echo "GOPATH=$HOME/go" >> $GITHUB_ENV

      - name: Append PATH variable
        run: |
          echo "/usr/local/go/bin" >> $GITHUB_PATH
          echo "$GOPATH/bin" >> $GITHUB_PATH
         
      - name: Install Geth
        run: ./install-geth.sh

      - name: Install Solidity
        run: ./install-solidity.sh

      - name: Install Protobuf
        run: ./install-protobuf.sh

      - name: Initialize and run Geth
        working-directory: ${{ github.workspace }}
        run: |
          # cd $GITHUB_WORKSPACE
          ./initialize-geth.sh
          ./run-geth.sh &

      - name: Run Bitcoin Core and ElectrumX
        working-directory: ${{ github.workspace }}
        run: ./run-bitcoin.sh &

      - name: Run pre-install script
        working-directory: ${{ github.workspace }}
        run: |
          ./pre-install.sh

      - name: Run install script
        working-directory: ${{ github.workspace }}
        run: |
          export E2E_TEST=true
          ./install.sh

      - name: Run Core and ECDSA clients
        working-directory: ${{ github.workspace }}
        run: |
          ./run-core-1.sh &
          ./run-ecdsa-1.sh &
          ./run-ecdsa-2.sh &
          ./run-ecdsa-3.sh &

      - name: Use Node.js 14.3.0
        uses: actions/setup-node@v2
        with:
          node-version: '14.3.0'

      # - name: Run E2E test scripts
      #   working-directory: ${{ github.workspace }}
      #   run: |
      #     nvm use 14.3.0
      #     echo "Using node: $(node -v)"
      #     ./run-e2e-test.sh

      - name: Run E2E test scripts
        working-directory: ${{ github.workspace }}
        run: ./run-e2e-test.sh