name: test geth

on:
  push: # TODO: remove
    branches:
      - 'rfc-18/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install Geth
        working-directory: ./deployments/local-setup-environment/provisioning/
        run: ./install-geth.sh

      - name: Initialize Geth
        run: ./initialize-geth.sh

      - name: Run Geth
        run: |
          ./run-geth.sh &
          ./loop.sh
